"""External empirical parameter optimization for the Phase-7 CEBP learner."""

from .objective import (
    CandidateEvaluation,
    HoldoutEvaluation,
    SeedEvaluation,
    FAILURE_LOSS,
    aggregate_candidate_evaluations,
    evaluate_candidate,
    evaluate_candidate_on_seed,
)
from .fixed_error_budget import (
    BUDGET_CAP_EXHAUSTED,
    BudgetThresholdEvaluation,
    FixedErrorBudgetTrial,
    PRECHECK_CAP_REJECTED,
    estimate_minimum_feasible_budget,
    fixed_error_threshold_ranking_key,
)
from .parameterization import (
    CandidateParameters,
    FixedBudgetCandidateParameters,
    FixedErrorCandidateParameters,
    DerivedCandidate,
    InvalidCandidateError,
    OptimizationConfig,
    PreflightResourceCheck,
    SearchSpace,
    candidate_from_manual_configs,
    candidate_to_end_to_end_config,
    derive_candidate,
    preflight_resource_check,
    minimum_practical_copy_budget,
    backend_sampling_count_limit,
    unsafe_backend_sampling_quantities,
    predict_tomography_pool_copies,
    sample_candidate,
)
from .progressive_search import (
    DEFAULT_FIXED_BUDGET_MIN_ERROR_IMPROVEMENT_RATIO,
    MAX_FIXED_BUDGET_MIN_ERROR_CANDIDATES,
    ProgressiveHalvingStageSummary,
    BudgetRefinementTrialSummary,
    FixedErrorComputationalDiagnostics,
    ProgressiveOptimizationResult,
    ProgressiveRoundSummary,
    ProgressiveSearchConfig,
    ProgressiveSearchMetadata,
    is_sufficient_relative_improvement,
    optimize_cebp_parameters_progressive,
    relative_loss_improvement,
)
from .search import CandidateRecord, OptimizationResult, optimize_cebp_parameters
from .specification import OptimizationMode, OptimizationObjective

__all__ = [
    "BUDGET_CAP_EXHAUSTED",
    "CandidateEvaluation",
    "CandidateParameters",
    "FixedBudgetCandidateParameters",
    "FixedErrorCandidateParameters",
    "CandidateRecord",
    "DerivedCandidate",
    "DEFAULT_FIXED_BUDGET_MIN_ERROR_IMPROVEMENT_RATIO",
    "FAILURE_LOSS",
    "HoldoutEvaluation",
    "InvalidCandidateError",
    "is_sufficient_relative_improvement",
    "MAX_FIXED_BUDGET_MIN_ERROR_CANDIDATES",
    "OptimizationConfig",
    "OptimizationMode",
    "OptimizationObjective",
    "OptimizationResult",
    "PreflightResourceCheck",
    "PRECHECK_CAP_REJECTED",
    "ProgressiveHalvingStageSummary",
    "BudgetRefinementTrialSummary",
    "BudgetThresholdEvaluation",
    "FixedErrorBudgetTrial",
    "FixedErrorComputationalDiagnostics",
    "ProgressiveOptimizationResult",
    "ProgressiveRoundSummary",
    "ProgressiveSearchConfig",
    "ProgressiveSearchMetadata",
    "SearchSpace",
    "SeedEvaluation",
    "candidate_from_manual_configs",
    "aggregate_candidate_evaluations",
    "candidate_to_end_to_end_config",
    "derive_candidate",
    "evaluate_candidate",
    "evaluate_candidate_on_seed",
    "estimate_minimum_feasible_budget",
    "fixed_error_threshold_ranking_key",
    "optimize_cebp_parameters",
    "optimize_cebp_parameters_progressive",
    "preflight_resource_check",
    "minimum_practical_copy_budget",
    "backend_sampling_count_limit",
    "unsafe_backend_sampling_quantities",
    "predict_tomography_pool_copies",
    "relative_loss_improvement",
    "sample_candidate",
]
